// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sklepix.Data;

#nullable disable

namespace Sklepix.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230712214517_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sklepix.Data.Entities.AisleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aisles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fridge aisle",
                            Name = "Fridges"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aisle at the left from the enterance",
                            Name = "Left aisle"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Aisle at the right from the enterance",
                            Name = "Right aisle"
                        });
                });

            modelBuilder.Entity("Sklepix.Data.Entities.AisleRowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AisleId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AisleId");

                    b.ToTable("AisleRows");
                });

            modelBuilder.Entity("Sklepix.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Breads, loafs",
                            Name = "Baking"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Drinks such as water, juices",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Frozen pizzas, fries, vegetables",
                            Name = "Frozen food"
                        });
                });

            modelBuilder.Entity("Sklepix.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AisleId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<float>("Count")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AisleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RowId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Sklepix.Data.Entities.AisleRowEntity", b =>
                {
                    b.HasOne("Sklepix.Data.Entities.AisleEntity", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");
                });

            modelBuilder.Entity("Sklepix.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Sklepix.Data.Entities.AisleEntity", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId");

                    b.HasOne("Sklepix.Data.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Sklepix.Data.Entities.AisleRowEntity", "Row")
                        .WithMany()
                        .HasForeignKey("RowId");

                    b.Navigation("Aisle");

                    b.Navigation("Category");

                    b.Navigation("Row");
                });
#pragma warning restore 612, 618
        }
    }
}
